# Copyright 2023 The Apollo Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto generated by buildtool of apollo

STATUS = 2

SOURCE = {
    "3rd-tf2" : {
        "path": "//third_party/tf2",
        "depends": [
            "3rd-boost",
            
        ],
    },
    "3rd-can-card-library" : {
        "path": "//third_party/can_card_library",
        "depends": [
            
        ],
    },
    "3rd-camera-library" : {
        "path": "//third_party/camera_library",
        "depends": [
            
        ],
    },
    "3rd-rtklib" : {
        "path": "//third_party/rtklib",
        "depends": [
            
        ],
    },
    "common-msgs" : {
        "path": "//modules/common_msgs",
        "depends": [
            "3rd-protobuf",
            
        ],
    },
    "cyber" : {
        "path": "//cyber",
        "depends": [
            "3rd-fastrtps",
            "3rd-gflags",
            "3rd-glog",
            "3rd-gtest",
            "3rd-nlohmann-json",
            "3rd-protobuf",
            "libncurses5-dev",
            "libtinyxml2-dev",
            "libuuid1",
            
        ],
    },
    "common" : {
        "path": "//modules/common",
        "depends": [
            "3rd-absl",
            "3rd-boost",
            "3rd-eigen3",
            "3rd-fastrtps",
            "3rd-gflags",
            "3rd-glog",
            "3rd-gtest",
            "3rd-nlohmann-json",
            "3rd-osqp",
            "3rd-protobuf",
            "libncurses5-dev",
            "libsqlite3-dev",
            "libtinyxml2-dev",
            "libuuid1",
            
        ],
    },
    "transform" : {
        "path": "//modules/transform",
        "depends": [
            "3rd-absl",
            "3rd-boost",
            "3rd-eigen3",
            "3rd-fastrtps",
            "3rd-gflags",
            "3rd-glog",
            "3rd-gtest",
            "3rd-nlohmann-json",
            "3rd-osqp",
            "3rd-protobuf",
            "3rd-yaml-cpp",
            "libncurses5-dev",
            "libsqlite3-dev",
            "libtinyxml2-dev",
            "libuuid1",
            
        ],
    },
    "drivers-camera" : {
        "path": "//modules/drivers/camera",
        "depends": [
            "3rd-absl",
            "3rd-adv-plat",
            "3rd-boost",
            "3rd-eigen3",
            "3rd-fastrtps",
            "3rd-ffmpeg",
            "3rd-gflags",
            "3rd-glog",
            "3rd-gtest",
            "3rd-nlohmann-json",
            "3rd-opencv",
            "3rd-osqp",
            "3rd-portaudio",
            "3rd-proj",
            "3rd-protobuf",
            "3rd-yaml-cpp",
            "libass9",
            "libdouble-conversion-dev",
            "libfdk-aac1",
            "libflann-dev",
            "libfreetype6",
            "libgl1-mesa-dev",
            "libglew-dev",
            "libgtk2.0-0",
            "libhdf5-dev",
            "libjsoncpp-dev",
            "libmp3lame0",
            "libncurses5-dev",
            "libnuma-dev",
            "libopenni0",
            "libopus0",
            "libpcap-dev",
            "libpcap0.8",
            "libqhull-dev",
            "libsqlite3-dev",
            "libtheora0",
            "libtiff5",
            "libtinyxml2-dev",
            "libusb-1.0-0",
            "libuuid1",
            "libvorbis0a",
            "libvorbisenc2",
            "libvpx-dev",
            "libwebp-dev",
            "libx264-dev",
            "libx265-dev",
            "libxml2-dev",
            "libxt-dev",
            
        ],
    },
    
}

BINARY = {
    "3rd-boost" : {
        "path": "//third_party/boost",
        "targets": [
            "@boost//:boost",
            
        ],
    },
    "bazel-extend-tools" : {
        "path": "//tools",
        "targets": [
            
        ],
    },
    "3rd-protobuf" : {
        "path": "//third_party/protobuf",
        "targets": [
            "@com_google_protobuf//:protobuf",
            
        ],
    },
    "libncurses5-dev" : {
        "path": "None",
        "targets": [
            "@ncurses5//:ncurses5",
            
        ],
    },
    "libuuid1" : {
        "path": "None",
        "targets": [
            "@uuid//:uuid",
            
        ],
    },
    "3rd-fastrtps" : {
        "path": "//third_party/fastrtps",
        "targets": [
            "@fastrtps//:fastrtps",
            
        ],
    },
    "3rd-glog" : {
        "path": "//third_party/glog",
        "targets": [
            "@com_github_google_glog//:glog",
            
        ],
    },
    "3rd-gflags" : {
        "path": "//third_party/gflags",
        "targets": [
            "@com_github_gflags_gflags//:gflags",
            
        ],
    },
    "3rd-gtest" : {
        "path": "//third_party/gtest",
        "targets": [
            "@com_google_googletest//:gtest",
            "@com_google_googletest//:gtest_main",
            
        ],
    },
    "3rd-nlohmann-json" : {
        "path": "//third_party/nlohmann_json",
        "targets": [
            "@com_github_nlohmann_json//:json",
            "@com_github_nlohmann_json//:single_json",
            
        ],
    },
    "libtinyxml2-dev" : {
        "path": "None",
        "targets": [
            "@tinyxml2//:tinyxml2",
            
        ],
    },
    "3rd-absl" : {
        "path": "//third_party/absl",
        "targets": [
            "@com_google_absl//:absl",
            
        ],
    },
    "libsqlite3-dev" : {
        "path": "None",
        "targets": [
            "@sqlite3//:sqlite3",
            
        ],
    },
    "3rd-eigen3" : {
        "path": "//third_party/eigen3",
        "targets": [
            "@eigen//:eigen",
            
        ],
    },
    "3rd-osqp" : {
        "path": "//third_party/osqp",
        "targets": [
            "@osqp//:osqp",
            
        ],
    },
    "3rd-yaml-cpp" : {
        "path": "//third_party/yaml_cpp",
        "targets": [
            "@com_github_jbeder_yaml_cpp//:yaml-cpp",
            
        ],
    },
    "3rd-proj" : {
        "path": "//third_party/proj",
        "targets": [
            "@proj//:proj",
            
        ],
    },
    "3rd-opencv" : {
        "path": "//third_party/opencv",
        "targets": [
            "@opencv//:core",
            "@opencv//:highgui",
            "@opencv//:imgcodecs",
            "@opencv//:imgproc",
            
        ],
    },
    "libgtk2.0-0" : {
        "path": "None",
        "targets": [
            "@libgtk2.0-0//:libgtk2.0-0",
            
        ],
    },
    "libwebp-dev" : {
        "path": "None",
        "targets": [
            "@libwebp-dev//:libwebp-dev",
            
        ],
    },
    "3rd-portaudio" : {
        "path": "//third_party/portaudio",
        "targets": [
            "@portaudio//:portaudio",
            
        ],
    },
    "3rd-ffmpeg" : {
        "path": "//third_party/ffmpeg",
        "targets": [
            "@ffmpeg//:avcodec",
            "@ffmpeg//:avformat",
            "@ffmpeg//:avutil",
            "@ffmpeg//:swscale",
            
        ],
    },
    "libx265-dev" : {
        "path": "None",
        "targets": [
            "@libx265-dev//:libx265-dev",
            
        ],
    },
    "libass9" : {
        "path": "None",
        "targets": [
            "@libass9//:libass9",
            
        ],
    },
    "libfdk-aac1" : {
        "path": "None",
        "targets": [
            "@libfdk-aac1//:libfdk-aac1",
            
        ],
    },
    "libmp3lame0" : {
        "path": "None",
        "targets": [
            "@libmp3lame0//:libmp3lame0",
            
        ],
    },
    "libopus0" : {
        "path": "None",
        "targets": [
            "@libopus0//:libopus0",
            
        ],
    },
    "libtheora0" : {
        "path": "None",
        "targets": [
            "@libtheora0//:libtheora0",
            
        ],
    },
    "libvorbis0a" : {
        "path": "None",
        "targets": [
            "@libvorbis0a//:libvorbis0a",
            
        ],
    },
    "libvorbisenc2" : {
        "path": "None",
        "targets": [
            "@libvorbisenc2//:libvorbisenc2",
            
        ],
    },
    "libvpx-dev" : {
        "path": "None",
        "targets": [
            "@libvpx-dev//:libvpx-dev",
            
        ],
    },
    "libx264-dev" : {
        "path": "None",
        "targets": [
            "@libx264-dev//:libx264-dev",
            
        ],
    },
    "libnuma-dev" : {
        "path": "None",
        "targets": [
            "@libnuma-dev//:libnuma-dev",
            
        ],
    },
    "3rd-adv-plat" : {
        "path": "//third_party/adv_plat",
        "targets": [
            "@adv_plat//:adv_plat",
            
        ],
    },
    "libusb-1.0-0" : {
        "path": "None",
        "targets": [
            "@libusb-1.0-0//:libusb-1.0-0",
            
        ],
    },
    "libopenni0" : {
        "path": "None",
        "targets": [
            "@libopenni0//:libopenni0",
            
        ],
    },
    "libfreetype6" : {
        "path": "None",
        "targets": [
            "@libfreetype6//:libfreetype6",
            
        ],
    },
    "libtiff5" : {
        "path": "None",
        "targets": [
            "@libtiff5//:libtiff5",
            
        ],
    },
    "libdouble-conversion-dev" : {
        "path": "None",
        "targets": [
            "@libdouble-conversion-dev//:libdouble-conversion-dev",
            
        ],
    },
    "libpcap0.8" : {
        "path": "None",
        "targets": [
            "@libpcap0.8//:libpcap0.8",
            
        ],
    },
    "libqhull-dev" : {
        "path": "None",
        "targets": [
            "@libqhull-dev//:libqhull-dev",
            
        ],
    },
    "libflann-dev" : {
        "path": "None",
        "targets": [
            "@libflann-dev//:libflann-dev",
            
        ],
    },
    "libglew-dev" : {
        "path": "None",
        "targets": [
            "@libglew-dev//:libglew-dev",
            
        ],
    },
    "libxml2-dev" : {
        "path": "None",
        "targets": [
            "@libxml2-dev//:libxml2-dev",
            
        ],
    },
    "libjsoncpp-dev" : {
        "path": "None",
        "targets": [
            "@libjsoncpp-dev//:libjsoncpp-dev",
            
        ],
    },
    "libhdf5-dev" : {
        "path": "None",
        "targets": [
            "@libhdf5-dev//:libhdf5-dev",
            
        ],
    },
    "libgl1-mesa-dev" : {
        "path": "None",
        "targets": [
            "@libgl1-mesa-dev//:libgl1-mesa-dev",
            
        ],
    },
    "libxt-dev" : {
        "path": "None",
        "targets": [
            "@libxt-dev//:libxt-dev",
            
        ],
    },
    "libpcap-dev" : {
        "path": "None",
        "targets": [
            "@libpcap-dev//:libpcap-dev",
            
        ],
    },
    
}